In [1]:
import cv2

In [2]:
img_color = cv2.imread("images/cat on laptop.jpg", cv2.IMREAD_COLOR)

if img_color is None:
    print("이미지 파일을 읽을 수 없습니다.")
    exit(1)

In [18]:
cv2.namedWindow('Color')
cv2.imshow('Color', img_color)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [3]:
img_gray = cv2.cvtColor(img_color, cv2.COLOR_BGR2GRAY)

cv2.imshow('GrayScale', img_gray)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [7]:
import numpy as np
import cv2 as cv

img_color = cv.imread("images/apple.png", cv.IMREAD_COLOR)
print(img_color.shape)

height, width = img_color.shape[:2]
print(height, width)

(267, 400, 3)
267 400


In [6]:
img_gray = np.zeros((height, width), np.uint8)
print(img_gray)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [16]:
for y in range(0, height):
    for x in range(0, width):

        b = img_color.item(y, x, 0)
        g = img_color.item(y, x, 1)
        r = img_color.item(y, x, 2)

        gray = int(r*0.2126 + g*0.7152 + b*0.0722)

        img_gray.itemset((y, x), gray)

img_result = cv.cvtColor(img_gray, cv.COLOR_GRAY2BGR)

cv.imshow('Grayscale', img_gray)
cv.imshow('Gray2BGR', img_result)
cv.waitKey(0)
cv.destroyAllWindows()

In [12]:
# 위의 수작업 전환 방식 말고 아래의 간단한 방법으로도 가능하다
# img_gray = cv.cvtColor(img_color, cv.COLOR_BGR2GRAY)
# img_result = cv.cvtColor(img_gray, cv.COLOR_GRAY2BGR)

In [14]:
for y in range(150, 201):
    for x in range(200, 251):

        img_result.itemset((y, x, 0), 0) # B
        img_result.itemset((y, x, 1), 255) # G
        img_result.itemset((y, x, 2), 0) # R

cv.imshow('Color', img_color)
cv.imshow('Result', img_result)
cv.waitKey(0)
cv.destroyAllWindows()